// <auto-generated />
namespace SongsDBLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addsongurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsongurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081007258_add song url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
